--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CATEGORIES (
		CATEGORY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		NAME VARCHAR(255 OCTETS) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN USERSPACE1
	COMPRESS NO;

CREATE TABLE ORDERS (
		ORDER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		TICKET_ID INTEGER NOT NULL, 
		BUYER_ID INTEGER NOT NULL, 
		TOTAL_PRICE DECIMAL(19 , 2) NOT NULL, 
		DATE_ORDERED TIMESTAMP NOT NULL, 
		SHIP_NAME VARCHAR(255 OCTETS) NOT NULL, 
		SHIP_ADDRESS_LINE_1 VARCHAR(255 OCTETS) NOT NULL, 
		SHIP_ADDRESS_LINE_2 VARCHAR(255 OCTETS), 
		SHIP_CITY VARCHAR(255 OCTETS) NOT NULL, 
		SHIP_STATE VARCHAR(255 OCTETS) NOT NULL, 
		SHIP_ZIP CHAR(5 OCTETS) NOT NULL, 
		DELIVERY_ETA BIGINT NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN USERSPACE1
	COMPRESS NO;

CREATE TABLE TICKETS (
		TICKET_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		SELLER_ID INTEGER NOT NULL, 
		CATEGORY_ID INTEGER NOT NULL, 
		TITLE VARCHAR(255 OCTETS) NOT NULL, 
		DESCRIPTION VARCHAR(255 OCTETS) NOT NULL, 
		PRICE DECIMAL(19 , 2) NOT NULL, 
		DATE BIGINT NOT NULL, 
		CREATED_AT TIMESTAMP NOT NULL, 
		SOLD SMALLINT NOT NULL DEFAULT 0, 
		SELLER_NAME VARCHAR(255 OCTETS) NOT NULL, 
		SELLER_ADDRESS_LINE_1 VARCHAR(255 OCTETS) NOT NULL, 
		SELLER_ADDRESS_LINE_2 VARCHAR(255 OCTETS), 
		SELLER_CITY VARCHAR(255 OCTETS) NOT NULL, 
		SELLER_STATE VARCHAR(255 OCTETS) NOT NULL, 
		SELLER_ZIP CHAR(5 OCTETS) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN USERSPACE1
	COMPRESS NO;

CREATE TABLE USERS (
		USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		EMAIL VARCHAR(50 OCTETS) NOT NULL, 
		PASSWORD CHAR(60 OCTETS) NOT NULL, 
		USERNAME VARCHAR(70 OCTETS) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN USERSPACE1
	COMPRESS NO;

ALTER TABLE CATEGORIES ADD CONSTRAINT SQL170414193133760 PRIMARY KEY
	(CATEGORY_ID);

ALTER TABLE ORDERS ADD CONSTRAINT SQL170513004021300 PRIMARY KEY
	(ORDER_ID);

ALTER TABLE TICKETS ADD CONSTRAINT SOLD_BOOLEAN CHECK ( SOLD = 0 or SOLD = 1 );

ALTER TABLE TICKETS ADD CONSTRAINT SQL170513025357400 PRIMARY KEY
	(TICKET_ID);

ALTER TABLE USERS ADD CONSTRAINT EMAIL UNIQUE
	(EMAIL);

ALTER TABLE USERS ADD CONSTRAINT SQL170329144153240 PRIMARY KEY
	(USER_ID);

ALTER TABLE ORDERS ADD CONSTRAINT TICKETS_FK FOREIGN KEY
	(TICKET_ID)
	REFERENCES TICKETS
	(TICKET_ID);

ALTER TABLE ORDERS ADD CONSTRAINT USERS_FK FOREIGN KEY
	(BUYER_ID)
	REFERENCES USERS
	(USER_ID);

ALTER TABLE TICKETS ADD CONSTRAINT CATEGORY_FK FOREIGN KEY
	(CATEGORY_ID)
	REFERENCES CATEGORIES
	(CATEGORY_ID);

ALTER TABLE TICKETS ADD CONSTRAINT USERS_FK FOREIGN KEY
	(SELLER_ID)
	REFERENCES USERS
	(USER_ID)
	ON DELETE CASCADE;

INSERT INTO DB2INST1.CATEGORIES (NAME) VALUES ('Music');

INSERT INTO DB2INST1.CATEGORIES (NAME) VALUES ('Sports');

INSERT INTO DB2INST1.CATEGORIES (NAME) VALUES ('Arts & Theater');

INSERT INTO DB2INST1.CATEGORIES (NAME) VALUES ('Family');

INSERT INTO DB2INST1.CATEGORIES (NAME) VALUES ('Other');